### ISSUE TITLE
Issue running vSphere provider and Fog

### ISSUE THREAD

**Issue by lanceblais** [fog/fog#2351]
I'm not sure what's wrong here. Are there known issues with Fog and vSphere appliances?

``` bash
2.0.0-p247 :001 > require 'fog'
[fog][WARNING] Unable to load the 'unf' gem. Your AWS strings may not be properly encoded.
 => true 
2.0.0-p247 :002 > 
2.0.0-p247 :003 >   compute = Fog::Compute.new(
2.0.0-p247 :004 >     :provider => 'vSphere',
2.0.0-p247 :005 >     :vsphere_username => myusername,
2.0.0-p247 :006 >     :vsphere_password => mypassword,
2.0.0-p247 :007 >     :vsphere_server   => serverip,
2.0.0-p247 :008 >     :vsphere_expected_pubkey_hash => hash,
2.0.0-p247 :009 >     )
 => #<Fog::Compute::Vsphere::Real:70207033816940 [...]> 
2.0.0-p247 :010 > 
2.0.0-p247 :011 >   compute.servers
Fog::Compute::Vsphere::NotFound: 14 was not found
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/fog-1.18.0/lib/fog/vsphere/requests/compute/get_virtual_machine.rb:27:in `get_vm_ref'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/fog-1.18.0/lib/fog/vsphere/requests/compute/list_vm_interfaces.rb:32:in `list_vm_interfaces'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/fog-1.18.0/lib/fog/vsphere/models/compute/interfaces.rb:18:in `all'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/fog-1.18.0/lib/fog/core/collection.rb:141:in `lazy_load'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/fog-1.18.0/lib/fog/core/collection.rb:15:in `empty?'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/fog-1.18.0/lib/fog/core/collection.rb:86:in `block in inspect'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/formatador-0.2.4/lib/formatador.rb:92:in `indent'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/fog-1.18.0/lib/fog/core/collection.rb:79:in `inspect'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/fog-1.18.0/lib/fog/core/model.rb:29:in `block (2 levels) in inspect'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/fog-1.18.0/lib/fog/core/model.rb:29:in `map'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/fog-1.18.0/lib/fog/core/model.rb:29:in `block in inspect'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/formatador-0.2.4/lib/formatador.rb:92:in `indent'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/fog-1.18.0/lib/fog/core/model.rb:26:in `inspect'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/fog-1.18.0/lib/fog/core/collection.rb:89:in `block (3 levels) in inspect'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/fog-1.18.0/lib/fog/core/collection.rb:17:in `map'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/fog-1.18.0/lib/fog/core/collection.rb:17:in `map'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/fog-1.18.0/lib/fog/core/collection.rb:89:in `block (2 levels) in inspect'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/formatador-0.2.4/lib/formatador.rb:92:in `indent'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/fog-1.18.0/lib/fog/core/collection.rb:88:in `block in inspect'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/formatador-0.2.4/lib/formatador.rb:92:in `indent'
    from /Users/lanceblais/.rvm/gems/ruby-2.0.0-p247/gems/fog-1.18.0/lib/fog/core/collection.rb:79:in `inspect'
    from /Users/lanceblais/.rvm/rubies/ruby-2.0.0-p247/bin/irb:13:in `<main>'2.0.0-p247 :012 > 
```

**Comment by Karunamon** [comment]
I'm unsure if this is helpful or not, but I ran into a bug identical to this one, and it was because there was somehow a 'junk' VM in the datacenter that didn't have a lot of its required options set. (For instance, it had a nil hostname, ipaddress, and guest_id).

It didn't show in the web UI or the VIM client, so I killed it off with rbvmomi, and all is well :)

**Comment by geemus** [comment]
@Karunamon ah, I could see how that would be problematic. Thanks for sharing your fix!

**Comment by nirvdrum** [comment]
@Karunamon I don't suppose you could think of a way that we could maybe validate instance correctness based on your experience, could you?  If so, that'd allow us to provide better error messaging in those sorts of cases.
