### ISSUE TITLE
Exception raised in Google#get_target_pool_health when instance is terminated

### ISSUE THREAD

**Issue by dacamp** [fog/fog#3114]
Google instances can be terminated, yet still in a Target Pool.  A `Fog::Errors::Error` exception is raised as 'resource is not ready', which prevents you from getting health for all other instances in that Target Pool.

Here's how I'm calling Target Pool `#get_health`
```
  if (t = load_balancers.target_pools.get(n)) && t.get_health.any?
          Hash[*t.get_health.map{|i, h|
                 i = i.split_link if split
                 [i, {:state => h.first['healthState'], :ip_address => h.first['ipAddress'] }]
               }.flatten]
  end
```

And the backtrace
```
#<Fog::Errors::Error: The resource 'projects/<PROJECT>/zones/us-central1-b/instances/<INSTANCE>' is not ready>
/Users/dacamp/.rvm/gems/ruby-2.0.0-p481/gems/fog-1.23.0/lib/fog/google/compute.rb:179:in `build_excon_response'
/Users/dacamp/.rvm/gems/ruby-2.0.0-p481/gems/fog-1.23.0/lib/fog/google/compute.rb:959:in `build_response'
/Users/dacamp/.rvm/gems/ruby-2.0.0-p481/gems/fog-1.23.0/lib/fog/google/requests/compute/get_target_pool_health.rb:21:in `block in get_target_pool_health'
/Users/dacamp/.rvm/gems/ruby-2.0.0-p481/gems/fog-1.23.0/lib/fog/google/requests/compute/get_target_pool_health.rb:19:in `map'
/Users/dacamp/.rvm/gems/ruby-2.0.0-p481/gems/fog-1.23.0/lib/fog/google/requests/compute/get_target_pool_health.rb:19:in `get_target_pool_health'
/Users/dacamp/.rvm/gems/ruby-2.0.0-p481/gems/fog-1.23.0/lib/fog/google/models/compute/target_pool.rb:79:in `get_health'
```

**Comment by plribeiro3000** [comment]
I'm closing this issue in favor of fog/fog-google#41.

If you have something to share, please do so there. Thanks!
