### ISSUE TITLE
Sakuracloud changes have broken require / incorrect dependencies

### ISSUE THREAD

**Issue by tokengeek** [fog/fog#3156]
As of e8a9ecaf7d6616b8031b68657a5c911c5c7fcc30...

```
$ bundle exec fog
/Users/paul/code/fog/lib/fog/bin.rb:84:in `require': cannot load such file -- fog/bin/sakuracloud (LoadError)
	from /Users/paul/code/fog/lib/fog/bin.rb:84:in `<top (required)>'
	from /Users/paul/code/fog/bin/fog:37:in `require'
	from /Users/paul/code/fog/bin/fog:37:in `<top (required)>'
	from /Users/paul/.gem/ruby/2.1.2/bin/fog:23:in `load'
	from /Users/paul/.gem/ruby/2.1.2/bin/fog:23:in `<main>'
```

**Comment by plribeiro3000** [comment]
@tokengeek @sawanoboly Should fog/fog-sakuracloud#6 close this?

[Fog `.gemspec`](https://github.com/fog/fog/blob/master/fog.gemspec#L60) was updated also.

**Comment by sawanoboly** [comment]
Sure, thanks.

**Comment by plribeiro3000** [comment]
Closing. Tnx @sawanoboly !

**Comment by geemus** [comment]
Thanks!

**Comment by plribeiro3000** [comment]
Opss. Forgot to close it. =s

**Comment by geemus** [comment]
Thanks!
