### ISSUE TITLE
Undefined namespace prefix: //soapenv:Body/* (Nokogiri::XML::XPath::SyntaxError)

### ISSUE THREAD

**Issue by obazoud** [fog/fog#3239]
I try to connect to vsphere 5.5 with fog:

```
require 'fog'

f = Fog::Compute.new(
  provider: 'vsphere',
  vsphere_username: 'xxx',
  vsphere_password: 'xxx',
  vsphere_server: 'xxx.xxx.xxx.xxx',
  vsphere_port: 'xxx',
  vsphere_ssl: true,
  vsphere_expected_pubkey_hash: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  vsphere_rev: '5.5'
)

puts f
```

I got the following stack trace at line "Fog::Compute.new..."

```
/home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/nokogiri-1.6.4/lib/nokogiri/xml/node.rb:159:in `evaluate': Undefined namespace prefix: //soapenv:Body/* (Nokogiri::XML::XPath::SyntaxError)
    from /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/nokogiri-1.6.4/lib/nokogiri/xml/node.rb:159:in `block in xpath'
    from /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/nokogiri-1.6.4/lib/nokogiri/xml/node.rb:150:in `map'
    from /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/nokogiri-1.6.4/lib/nokogiri/xml/node.rb:150:in `xpath'
    from /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/rbvmomi-1.8.2/lib/rbvmomi/trivial_soap.rb:112:in `request'
    from /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:87:in `call'
    from /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/rbvmomi-1.8.2/lib/rbvmomi/basic_types.rb:205:in `_call'
    from /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/rbvmomi-1.8.2/lib/rbvmomi/basic_types.rb:74:in `block (2 levels) in init'
    from /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/rbvmomi-1.8.2/lib/rbvmomi/vim.rb:68:in `serviceContent'
    from /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/fog-1.24.0/lib/fog/vsphere/compute.rb:370:in `negotiate_revision'
    from /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/fog-1.24.0/lib/fog/vsphere/compute.rb:349:in `initialize'
    from /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/fog-core-1.24.0/lib/fog/core/service.rb:115:in `new'
    from /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/fog-core-1.24.0/lib/fog/core/service.rb:115:in `new'
    from /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/fog-core-1.24.0/lib/fog/compute.rb:58:in `new'
    from test.rb:5:in `<main>'

```

Any idea ?
Thanks

**Comment by gogundare** [comment]
Thanks obazoud for this, you've just saved me from a huge headache that we have been having in our environment for months. Thanks Man
