### ISSUE TITLE
Fog 1.25.0 gets Excon warning

### ISSUE THREAD

**Issue by mtimofiiv** [fog/fog#3288]
Our Amazon EC3 uploading seems to have broken as of the 1.25.0 release. Ruby 2.1.4 and Rails 4.1.8. The only message that comes up is this stack trace and warning from Excon.

Version-locking to 1.24.0 fixed the issue.

```
[excon][WARNING] Excon requests with a :request_block can not be :idempotent.
/app/vendor/bundle/ruby/2.1.0/gems/excon-0.41.0/lib/excon/middlewares/idempotent.rb:7:in `error_call'
/app/vendor/bundle/ruby/2.1.0/gems/excon-0.41.0/lib/excon/middlewares/base.rb:10:in `error_call'
/app/vendor/bundle/ruby/2.1.0/gems/excon-0.41.0/lib/excon/middlewares/base.rb:10:in `error_call'
/app/vendor/bundle/ruby/2.1.0/gems/excon-0.41.0/lib/excon/connection.rb:255:in `rescue in request'
/app/vendor/bundle/ruby/2.1.0/gems/excon-0.41.0/lib/excon/connection.rb:203:in `request'
/app/vendor/bundle/ruby/2.1.0/gems/fog-core-1.25.0/lib/fog/core/connection.rb:63:in `request'
/app/vendor/bundle/ruby/2.1.0/gems/fog-xml-0.1.1/lib/fog/xml/connection.rb:9:in `request'
/app/vendor/bundle/ruby/2.1.0/gems/fog-1.25.0/lib/fog/aws/storage.rb:521:in `_request'
/app/vendor/bundle/ruby/2.1.0/gems/fog-1.25.0/lib/fog/aws/storage.rb:516:in `request'
/app/vendor/bundle/ruby/2.1.0/gems/fog-1.25.0/lib/fog/aws/requests/storage/put_object.rb:31:in `put_object'
/app/vendor/bundle/ruby/2.1.0/gems/fog-1.25.0/lib/fog/aws/models/storage/file.rb:208:in `save'
/app/vendor/bundle/ruby/2.1.0/gems/fog-core-1.25.0/lib/fog/core/collection.rb:50:in `create'
/app/vendor/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/storage/fog.rb:261:in `store'
/app/vendor/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/storage/fog.rb:80:in `store!'
/app/vendor/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:59:in `block in store!'
/app/vendor/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/callbacks.rb:17:in `with_callbacks'
/app/vendor/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:58:in `store!'
/app/vendor/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:375:in `store!'
/app/vendor/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:207:in `store_file!'
```

Let me know if you need further details!

**Comment by pencilcheck** [comment]
the latest fog is still depending on the older excon, still getting errors about excon, have to manually include excon in Gemfile, please change the dependencies.

**Comment by geemus** [comment]
Bumped here: https://github.com/fog/fog-core/commit/8d5f59da1111d5d7770957d1d047569c26bce6fa

**Comment by pencilcheck** [comment]
Thx :+1:
