### ISSUE TITLE
Invalid XML Character in S3 Response

### ISSUE THREAD

**Issue by KenBackupify** [fog/fog#3315]
I'm trying to get all the versions in a directory, but the code is encountering ```xmlParseCharRef: invalid xmlChar value 26 (Nokogiri::XML::SyntaxError)``` when I call the versions function on the directory. Looking at the raw XML, it looks like there is some invalid characters in the response...a couple keys have those diamond-with-question-marks characters in them, which I'm guessing is what Nokogiri is dying on. Here's a sample traceback:

```
"/myapp/shared/bundle/ruby/2.1.0/gems/nokogiri-1.5.11/lib/nokogiri/xml/sax/push_parser.rb:47:in `native_write'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/nokogiri-1.5.11/lib/nokogiri/xml/sax/push_parser.rb:47:in `write'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/fog-1.23.0/lib/fog/xml/sax_parser_connection.rb:31:in `block in request'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/response.rb:87:in `call'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/response.rb:87:in `parse'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/middlewares/response_parser.rb:6:in `response_call'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/connection.rb:363:in `response'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/connection.rb:233:in `request'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/middlewares/idempotent.rb:22:in `error_call'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/middlewares/base.rb:10:in `error_call'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/middlewares/base.rb:10:in `error_call'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/connection.rb:253:in `rescue in request'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/connection.rb:201:in `request'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/middlewares/idempotent.rb:22:in `error_call'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/middlewares/base.rb:10:in `error_call'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/middlewares/base.rb:10:in `error_call'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/connection.rb:253:in `rescue in request'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/connection.rb:201:in `request'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/middlewares/idempotent.rb:22:in `error_call'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/middlewares/base.rb:10:in `error_call'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/middlewares/base.rb:10:in `error_call'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/connection.rb:253:in `rescue in request'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/excon-0.39.5/lib/excon/connection.rb:201:in `request'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/fog-1.23.0/lib/fog/xml/sax_parser_connection.rb:35:in `request'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/fog-1.23.0/lib/fog/xml/connection.rb:17:in `request'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/fog-1.23.0/lib/fog/aws/storage.rb:535:in `request'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/fog-1.23.0/lib/fog/aws/requests/storage/get_bucket_object_versions.rb:54:in `get_bucket_object_versions'", 
"/myapp/shared/bundle/ruby/2.1.0/gems/fog-1.23.0/lib/fog/aws/models/storage/versions.rb:17:in `all'"
```

Is there a way for me to get around this through Fog, maybe a way to have Fog replace invalid characters during the parsing?

**Comment by plribeiro3000** [comment]
closed in favor of fog/fog-aws#8
