### ISSUE TITLE
Breaking change on initialize?

### ISSUE THREAD

**Issue by mdarby** [fog/fog#3404]
This worked before the 1.27 release. Must we now manually pass in auth info if it's in a ~/.fog file?

```
irb: Fog::Rackspace::NetworkingV2.new
ArgumentError: wrong number of arguments (0 for 1)
	from /Users/mdarby/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/fog-core-1.27.3/lib/fog/formatador.rb:6:in `initialize'
	from /Users/mdarby/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/fog-core-1.27.3/lib/fog/core/model.rb:24:in `new'
	from /Users/mdarby/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/fog-core-1.27.3/lib/fog/core/model.rb:24:in `inspect'
	from /Users/mdarby/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/fog-core-1.27.3/lib/fog/core/service.rb:14:in `block in inspect'
	from /Users/mdarby/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/fog-core-1.27.3/lib/fog/core/service.rb:14:in `map'
	from /Users/mdarby/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/fog-core-1.27.3/lib/fog/core/service.rb:14:in `inspect'
	from /Users/mdarby/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/fog-core-1.27.3/lib/fog/core/service.rb:14:in `block in inspect'
	from /Users/mdarby/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/fog-core-1.27.3/lib/fog/core/service.rb:14:in `map'
	from /Users/mdarby/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/fog-core-1.27.3/lib/fog/core/service.rb:14:in `inspect'
	from /Users/mdarby/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/commands/console.rb:90:in `start'
	from /Users/mdarby/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/commands/console.rb:9:in `start'
	from /Users/mdarby/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/mdarby/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/mdarby/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by mdarby** [comment]
Even with credentials passed in...
![1 bundle exec rails c ruby 2015-01-17 11-04-46](https://cloud.githubusercontent.com/assets/2805/5789446/146af08c-9e39-11e4-8d1b-5732325069c2.jpg)

**Comment by mdarby** [comment]
Seems that this was was introduced in https://github.com/fog/fog-core/commit/55e82a37f43ea012ae9c5a1e088edb8a27484c38#diff-0cb327cd048d944b77e791db03dec94c

**Comment by mdarby** [comment]
@starbelly any insight on this?

**Comment by starbelly** [comment]
Are you sure what you're running is at `55e82a3`?.  It's croaking on a constructor call but in that revision  Fog::Formatador is a module, not a class. Please double check that and try this with HEAD as well, some other bugs related to Fog::Formatador have been fixed in the last day or so as well that you will no doubt run into.

**Comment by mdarby** [comment]
I'm just running the latest gem, as are my users.

**Comment by plribeiro3000** [comment]
@mdarby I think the changes @starbelly suggested are not on the latest gem but on the master instead.
Could you try it out?

**Comment by plribeiro3000** [comment]
Possible a duplicate of fog/fog-core#123 fog/fog-core#124 fog/fog-core#121 fog/fog-core#119.

**Comment by mdarby** [comment]
Yep, this is a dup. I'll close.
