### ISSUE TITLE
[vsphere] fog fails to find nested resource pools

### ISSUE THREAD

**Issue by asebastian-r7** [fog/fog#3579]
We are currently having an issue with cloning to a nested resource pool. I believe the root of the problem lies in the get_resource_pool method not supporting nested resource pools.  

This works
```bash
f = Fog::Compute.new(provider: "vsphere", etc)
f.get_resource_pool("Birds", "My cluster", "my.datacenter")
=> {:id=>"resgroup-28592", :name=>"Birds", :configured_memory_mb=>4837888, :overall_status=>"green", :cluster=>"My cluster", :datacenter=>"my.datacenter"}
```

This does not
```bash
f = Fog::Compute.new(provider: "vsphere", etc)
f.get_resource_pool("Birds/Ducks", "My cluster", "my.datacenter")

/Users/asebastian/.rvm/gems/ruby-2.2.2/gems/fog-1.30.0/lib/fog/vsphere/requests/compute/get_resource_pool.rb:16:in `get_raw_resource_pool': undefined method `resourcePool' for nil:NilClass (NoMethodError)
	from /Users/asebastian/.rvm/gems/ruby-2.2.2/gems/fog-1.30.0/lib/fog/vsphere/requests/compute/get_resource_pool.rb:6:in `get_resource_pool'
	from resource_pool_test.rb:11:in `initialize'
	from resource_pool_test.rb:22:in `new'
	from resource_pool_test.rb:22:in `<main>'
```

**Comment by geemus** [comment]
@nirvdrum could you take a look when you get a moment? Thanks!
