### ISSUE TITLE
Error: cannot load such file -- fog/xenserver

### ISSUE THREAD

**Issue by synth** [fog/fog#3965]
I get this when precompiling assets during a capistrano deployment to an integration server. I am not even using xenserver and thus the gem is not there. Looking at the fog line, it seems to require it nonetheless. 

Shouldn't there be a xenserver.rb file somewhere in this repo so it doesn't crash?

When I manually remove 'fog/xenserver.rb' from fog.rb, the precompile successfully completes.

Using  `fog (v1.41.0)`

```shell
$ bundle exec rake assets:precompile
rake aborted!
LoadError: cannot load such file -- fog/xenserver
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `require'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `block in require'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `require'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/fog-1.38.0/lib/fog.rb:62:in `<top (required)>'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `require'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `block in require'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `require'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/storage/fog.rb:3:in `<top (required)>'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `require'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `block in require'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `require'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/storage.rb:9:in `<top (required)>'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `require'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `block in require'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247:in `require'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave.rb:78:in `<top (required)>'
/home/web/.rvm/gems/ruby-2.2.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/home/web/.rvm/gems/ruby-2.2.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/home/web/.rvm/gems/ruby-2.2.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/home/web/.rvm/gems/ruby-2.2.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/home/web/.rvm/gems/ruby-2.2.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/home/web/.rvm/gems/ruby-2.2.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/home/web/.rvm/gems/ruby-2.2.4/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/home/web/sites/mysite.com/releases/20170912085809/config/application.rb:10:in `<top (required)>'
/home/web/sites/mysite.com/releases/20170912085809/Rakefile:5:in `require'
/home/web/sites/mysite.com/releases/20170912085809/Rakefile:5:in `<top (required)>'
/home/web/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
```

**Comment by geemus** [comment]
Hey, fog (for historical reasons) is a sort of metagem that requires the various provider gems (such as fog-xenserver, which should fulfill this requirement). I'm not sure why that wouldn't be working as the dependency should cause it to install fog-xenserver gem as well. That said, it depends a bit on which providers you actually need/want. Although fog includes many other things, you can also use the individual fog provider gems directly to have fewer dependencies. For example to use amazon stuff you could just replace the fog gem with fog-aws and require that. Hope that helps, but certainly happy to discuss further.

**Comment by plribeiro3000** [comment]
From line 5 of your stacktrace it seems you might have a misconfiguration since you say you are using version `1.41.0` of `fog` but the stacktrace actually says is another version `1.38.0`.

Could you please double check which fog version you are using?

**Comment by plribeiro3000** [comment]
Also, could you provide more context, like:

* which providers you are using
* the gems you have installed with version
* if the problem happens only when compiling or if you can't also start the server or a console

This should help us narrow down the issue.

**Comment by plribeiro3000** [comment]
Closing by lack of feedback. Feel free to reopen and/or comment to continue the discussion.

**Comment by geemus** [comment]
Thanks!
