### ISSUE TITLE
[openstack][pike] Compute[:openstack].servers doesn't work

### ISSUE THREAD

**Issue by aibondarenko** [fog/fog#3979]
Trying to connect locally deployed openstack (pike) with fog 1.42.0.

Firstly, curl connection works well with the command: https://hastebin.com/fihojuqize.scala

With this in mind, i've created fog credentials file: https://hastebin.com/hexanixucu.scala and run

fog openstack
Compute[:openstack].servers

This leads to an error like [full text here](https://hastebin.com/bucugizipi.php)
```
  :status        => 302
  :status_line   => "HTTP/1.1 302 Found\r\n"

    from /var/lib/gems/2.3.0/gems/excon-0.60.0/lib/excon/middlewares/expects.rb:7:in `response_call'
    from /var/lib/gems/2.3.0/gems/excon-0.60.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
    from /var/lib/gems/2.3.0/gems/excon-0.60.0/lib/excon/connection.rb:414:in `response'
    from /var/lib/gems/2.3.0/gems/excon-0.60.0/lib/excon/connection.rb:263:in `request'
    from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/connection.rb:81:in `request'
    from /var/lib/gems/2.3.0/gems/fog-openstack-0.1.23/lib/fog/openstack.rb:610:in `get_version'
    from /var/lib/gems/2.3.0/gems/fog-openstack-0.1.23/lib/fog/openstack.rb:583:in `get_supported_microversion'
    from /var/lib/gems/2.3.0/gems/fog-openstack-0.1.23/lib/fog/openstack/core.rb:122:in `set_microversion'
    from /var/lib/gems/2.3.0/gems/fog-openstack-0.1.23/lib/fog/openstack/core.rb:212:in `authenticate'
    from /var/lib/gems/2.3.0/gems/fog-openstack-0.1.23/lib/fog/compute/openstack.rb:397:in `initialize'
    from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:115:in `new'
    from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:115:in `new'
    from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/services_mixin.rb:16:in `new'
    from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/compute.rb:54:in `new'
    from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/services_mixin.rb:4:in `[]'
    from (irb):1:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/fog-1.42.0/bin/fog:76:in `block in <top (required)>'
    from /var/lib/gems/2.3.0/gems/fog-1.42.0/bin/fog:76:in `catch'
    from /var/lib/gems/2.3.0/gems/fog-1.42.0/bin/fog:76:in `<top (required)>'
    from /usr/local/bin/fog:23:in `load'
    from /usr/local/bin/fog:23:in `<main>
```
First request to "/identity/v3/auth/tokens" was complete, but overall result is bad..

Worth to be mentioned - i've cntlm proxy configured.

**Comment by geemus** [comment]
Hey, I think you may have better luck if you ask on the fog/fog-openstack repo, I think the main experts pay closer attention to that. Sorry for the redirection, but hope they can help. Thanks!

**Comment by aibondarenko** [comment]
Thank you for your pointers,
it seems, that trouble exactly there..
