### ISSUE TITLE
[25430] ! Unable to load application: Bundler::GemRequireError: There was an error while trying to load the gem 'fog'.

### ISSUE THREAD

**Issue by ethicalmohit** [fog/fog#3988]
I am getting error while running the app. I have installed fog gem explicitly also. I am not sure where I am going wrong.

Command: `gem install fog; RAILS_ENV="production" bundle exec puma -e "production" -d`

Error:
```
[25430] ! Unable to load application: Bundler::GemRequireError: There was an error while trying to load the gem 'fog'.
Gem Load Error is: non-absolute home
Backtrace for gem load error is:
/usr/local/rvm/gems/ruby-2.3.1/gems/fog-core-1.45.0/lib/fog/core/cache.rb:94:in `expand_path'
/usr/local/rvm/gems/ruby-2.3.1/gems/fog-core-1.45.0/lib/fog/core/cache.rb:94:in `<class:Cache>'
/usr/local/rvm/gems/ruby-2.3.1/gems/fog-core-1.45.0/lib/fog/core/cache.rb:84:in `<module:Fog>'
/usr/local/rvm/gems/ruby-2.3.1/gems/fog-core-1.45.0/lib/fog/core/cache.rb:6:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/fog-core-1.45.0/lib/fog/core/model.rb:2:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/fog-core-1.45.0/lib/fog/core.rb:42:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/fog-1.41.0/lib/fog.rb:9:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
/home/ubuntu/code/example/current/config/application.rb:9:in `<top (required)>'
/home/ubuntu/code/example/current/config/environment.rb:2:in `require'
/home/ubuntu/code/example/current/config/environment.rb:2:in `<top (required)>'
config.ru:3:in `require'
config.ru:3:in `block in <main>'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.9/lib/rack/builder.rb:55:in `instance_eval'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.9/lib/rack/builder.rb:55:in `initialize'
config.ru:in `new'
config.ru:in `<main>'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.9/lib/rack/builder.rb:49:in `eval'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.9/lib/rack/builder.rb:49:in `new_from_string'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.9/lib/rack/builder.rb:40:in `parse_file'
/usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/lib/puma/configuration.rb:318:in `load_rackup'
/usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/lib/puma/configuration.rb:243:in `app'
/usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/lib/puma/runner.rb:138:in `load_and_bind'
/usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/lib/puma/cluster.rb:397:in `run'
/usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/lib/puma/launcher.rb:183:in `run'
/usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/lib/puma/cli.rb:77:in `run'
/usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/bin/puma:10:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/bin/puma:23:in `load'
/usr/local/rvm/gems/ruby-2.3.1/bin/puma:23:in `<main>'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Bundler Error Backtrace:
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'fog'. (Bundler::GemRequireError)
Gem Load Error is: non-absolute home
Backtrace for gem load error is:
/usr/local/rvm/gems/ruby-2.3.1/gems/fog-core-1.45.0/lib/fog/core/cache.rb:94:in `expand_path'
/usr/local/rvm/gems/ruby-2.3.1/gems/fog-core-1.45.0/lib/fog/core/cache.rb:94:in `<class:Cache>'
/usr/local/rvm/gems/ruby-2.3.1/gems/fog-core-1.45.0/lib/fog/core/cache.rb:84:in `<module:Fog>'
/usr/local/rvm/gems/ruby-2.3.1/gems/fog-core-1.45.0/lib/fog/core/cache.rb:6:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/fog-core-1.45.0/lib/fog/core/model.rb:2:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/fog-core-1.45.0/lib/fog/core.rb:42:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/fog-1.41.0/lib/fog.rb:9:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
/home/ubuntu/code/example/current/config/application.rb:9:in `<top (required)>'
/home/ubuntu/code/example/current/config/environment.rb:2:in `require'
/home/ubuntu/code/example/current/config/environment.rb:2:in `<top (required)>'
config.ru:3:in `require'
config.ru:3:in `block in <main>'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.9/lib/rack/builder.rb:55:in `instance_eval'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.9/lib/rack/builder.rb:55:in `initialize'
config.ru:in `new'
config.ru:in `<main>'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.9/lib/rack/builder.rb:49:in `eval'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.9/lib/rack/builder.rb:49:in `new_from_string'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.9/lib/rack/builder.rb:40:in `parse_file'
/usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/lib/puma/configuration.rb:318:in `load_rackup'
/usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/lib/puma/configuration.rb:243:in `app'
/usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/lib/puma/runner.rb:138:in `load_and_bind'
/usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/lib/puma/cluster.rb:397:in `run'
/usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/lib/puma/launcher.rb:183:in `run'
/usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/lib/puma/cli.rb:77:in `run'
/usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/bin/puma:10:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/bin/puma:23:in `load'
/usr/local/rvm/gems/ruby-2.3.1/bin/puma:23:in `<main>'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Bundler Error Backtrace:
	from /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:80:in `block (2 levels) in require'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
	from /home/ubuntu/code/example/current/config/application.rb:9:in `<top (required)>'
	from /home/ubuntu/code/example/current/config/environment.rb:2:in `require'
	from /home/ubuntu/code/example/current/config/environment.rb:2:in `<top (required)>'
	from config.ru:3:in `require'
	from config.ru:3:in `block in <main>'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.9/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.9/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.9/lib/rack/builder.rb:49:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.9/lib/rack/builder.rb:49:in `new_from_string'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.9/lib/rack/builder.rb:40:in `parse_file'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/lib/puma/configuration.rb:318:in `load_rackup'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/lib/puma/configuration.rb:243:in `app'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/lib/puma/runner.rb:138:in `load_and_bind'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/lib/puma/cluster.rb:397:in `run'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/lib/puma/launcher.rb:183:in `run'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/lib/puma/cli.rb:77:in `run'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/puma-3.11.3/bin/puma:10:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/puma:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/puma:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by plribeiro3000** [comment]
I've seen this erro before: #397 

Is HOME set?

**Comment by plribeiro3000** [comment]
I'm glad it worked. =)
